### ISSUE TITLE
Long downloads from a 'search' get a socket.error

### ISSUE THREAD

**Issue by tcj** [jjjake/internetarchive#109]
commandline example: `ia download --search="collection:tosec" | tee -a output.log`

once it hits a sizable file, it will:
```
Amiga_CDTV_TOSEC_2009_04_18 (8/189): dTraceback (most recent call last):
  File "/Users/user/src/internetarchive/build/lib/internetarchive/iacli/ia.py", line 102, in <module>
    main()
  File "/Users/user/src/internetarchive/build/lib/internetarchive/iacli/ia.py", line 99, in main
    ia_module.main(argv)
  File "/Users/user/src/internetarchive/internetarchive/iacli/ia_download.py", line 121, in main
    ignore_errors=True
  File "/Users/user/src/internetarchive/internetarchive/item.py", line 337, in download
    retries, ignore_errors)
  File "/Users/user/src/internetarchive/internetarchive/item.py", line 849, in download
    for chunk in response.iter_content(chunk_size=chunk_size):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
socket.error: [Errno 54] Connection reset by peer
```

**Comment by jjjake** [comment]
This should no longer be an issue after switch from the advanced search API to the scrape API.
