### ISSUE TITLE
ia does not close files after uploading them

### ISSUE THREAD

**Issue by jleclanche** [jjjake/internetarchive#115]
When uploading a lot of files at once this happens:

``` pytb
Traceback (most recent call last):
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 292, in ssl_wrap_socket
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/requests/adapters.py", line 376, in send
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 252, in connect
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 294, in ssl_wrap_socket
requests.packages.urllib3.exceptions.SSLError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/bin/ia", line 9, in <module>
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/internetarchive-1.0.0.dev8-py3.5.egg/internetarchive/cli/ia.py", line 122, in main
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/internetarchive-1.0.0.dev8-py3.5.egg/internetarchive/cli/ia_upload.py", line 169, in main
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/internetarchive-1.0.0.dev8-py3.5.egg/internetarchive/cli/ia_upload.py", line 57, in _upload_files
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/internetarchive-1.0.0.dev8-py3.5.egg/internetarchive/item.py", line 677, in upload
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/internetarchive-1.0.0.dev8-py3.5.egg/internetarchive/item.py", line 536, in upload_file
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
  File "/home/adys/.local/share/virtualenvs/tmp-309bac8c01e43fe/lib/python3.5/site-packages/requests/adapters.py", line 447, in send
requests.exceptions.SSLError: [Errno 24] Too many open files

```

**Comment by jleclanche** [comment]
I address this in #114

**Comment by jleclanche** [comment]
Actually it's not fully fixed by that commit, just slower to reproduce now... Im not sure where else there's dangling handles.

**Comment by wumpus** [comment]
ls /proc/<pid>/fd is your friend... you might be able to see a pattern in the filenames or something.

**Comment by jjjake** [comment]
I believe https://github.com/jjjake/internetarchive/pull/162 should address this issue. @jleclanche please comment if you continue to experience this issue in version > 1.1.0.dev1.
