### ISSUE TITLE
Timeout on downloading a search result 

### ISSUE THREAD

**Issue by kamal94** [jjjake/internetarchive#136]
I have a relatively large dataset to download (mainly of IDs). The query is "'سكر'". 
When I try either 
```
 for r in ia.search_items("'سكر'"):
     file.write(r['identifier']+ "\n")
```
or
``` ia search "'سكر'" -i > t3.txt ```
I get the following timeout error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='archive.org', port=443): Read timed out. (read timeout=12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='archive.org', port=443): Max retries exceeded with url: /services/search/beta/scrape.php?q=%27%D8%B3%D9%83%D8%B1%27&fields=identifier&size=10000 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='archive.org', port=443): Read timed out. (read timeout=12)",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/ia", line 9, in <module>
    load_entry_point('internetarchive==1.0.2', 'console_scripts', 'ia')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/internetarchive/cli/ia.py", line 131, in main
    sys.exit(ia_module.main(argv, session))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/internetarchive/cli/ia_search.py", line 64, in main
    for result in search:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/internetarchive/search.py", line 162, in __next__
    return self.iterator.__next__()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/internetarchive/search.py", line 107, in _scrape
    **self.request_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='archive.org', port=443): Max retries exceeded with url: /services/search/beta/scrape.php?q=%27%D8%B3%D9%83%D8%B1%27&fields=identifier&size=10000 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='archive.org', port=443): Read timed out. (read timeout=12)",))

Any ideas or workarounds?

**Comment by jjjake** [comment]
So it looks like that query is taking longer than 12 seconds unfortunately (and that is the timeout I have set in the client). I will look into resolving this by increasing the default timeout and providing an option for changing the timeout, or working with the developers in charge of search here at the Archive to see why this query is taking so long to run.

In the meantime, setting the size param to something smaller than the default of 10k should work:

```
for r in ia.search_items("'سكر'", params=dict(size=1000)):
    file.write(r['identifier']+ "\n")
```

I'll follow up here once we come up with a proper resolution.

Thanks for reporting the issue @kamal94, I appreciate it!

**Comment by willf** [comment]
jjake, I _think_ this is due to the increased cost of UTF-8 encoding/decoding. I suggest that you either increase the timeout or decrease the size when the number of bytes of the string doesn't equal the number of codepoints. I am seeing simple searches (like `سكر`) take about 12 seconds when other simple searches (like our favorite `nasa`) take 4 seconds. You could also, of course, decrease the size/increase the timeout across the board.

**Comment by kamal94** [comment]
Thank you @jjjake, ```params=dict(size=1000)``` fixed the timeout. Like @willf said, the delay is most probably due to the increased cost of Arabic text processing.
