### ISSUE TITLE
Error while searching for anything

### ISSUE THREAD

**Issue by kamal94** [jjjake/internetarchive#147]
```ia search "nasa" -n```

produces
```error: Expecting value: line 1 column 1 (char 0)```

This happens for whatever search I attempt.

Also in python:

```
>>> i = 0
>>> for r in ia.search_items("nasa"):
...     i+=1
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/internetarchive/search.py", line 197, in __next__
    return self.iterator.__next__()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/internetarchive/search.py", line 127, in _scrape
    j = r.json()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jjjake** [comment]
Thanks for the report @kamal94. We pushed a change over the weekend that broke the underlying API. This should now be fixed.

Please reopen this issue if you are still experiencing issues. Thanks!
