### ISSUE TITLE
Uploads (requests) timing out

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#149]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.5/http/client.py", line 905, in send
    self.sock.sendall(datablock)
  File "/usr/lib/python3.5/ssl.py", line 887, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python3.5/ssl.py", line 857, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 582, in write
    return self._sslobj.write(data)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/retry.py", line 255, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.5/http/client.py", line 905, in send
    self.sock.sendall(datablock)
  File "/usr/lib/python3.5/ssl.py", line 887, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python3.5/ssl.py", line 857, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 582, in write
    return self._sslobj.write(data)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(110, 'Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tubeup.py", line 250, in <module>
    main()
  File "./tubeup.py", line 243, in main
    identifier, meta = upload_ia(video)
  File "./tubeup.py", line 193, in upload_ia
    item.upload(vid_files, metadata=meta)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 718, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 583, in upload_file
    **request_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/session.py", line 343, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(110, 'Connection timed out'))
```

Could you possibly specify the default timeouts for uploading and triple it from, what I believe is the default 110 in requests?

Unless I'm mistaken in how I'm reading this. A script I maintain relies on your library and figured upping the threshold for timeouts would benefit others.

**Comment by jjjake** [comment]
Thanks for reporting your issue @vxbinaca, I appreciate it.

Note that you can specify your own timeout via the `request_kwargs` parameter in upload:

```
>>> from internetarchive import get_item
>>> item = get_item('<identifier>')
>>> r = item.upload('file.txt', request_kwargs=dict(timeout=300))
...
```

So, I think this is a documentation issue -- do you agree? Does this solution work for you?

**Comment by vxbinaca** [comment]
Tentatively closing this issue as adding ```request_kwargs=dict(timeout=300)``` to the script didn't break uploading, so I'm assuming it's been fixed.

Thanks. In case you're curious what we're using internetarchive for it's [this] (https://github.com/bibanon/tubeup).

**Comment by jjjake** [comment]
@vxbinaca: That is very cool! Please let me know if you ever run into any other issues.
