### ISSUE TITLE
Bug: delete --all fails on 1.0.8

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#151]
```ia delete Snydsnap_Youtube_Archive --all```

```
Deleting files from Snydsnap_Youtube_Archive
 deleting: [Cover] Fly me to the moon-omVL1YATrwA.annotations.xml
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/utils.py", line 752, in check_header_validity
    if not pat.match(value):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/cli/ia.py", line 155, in main
    sys.exit(ia_module.main(argv, session))
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/cli/ia_delete.py", line 129, in main
    retries=args['--retries'])
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/files.py", line 291, in delete
    prepared_request = request.prepare()
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/iarequest.py", line 80, in prepare
    queue_derive=self.queue_derive,
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/iarequest.py", line 96, in prepare
    self.prepare_headers(headers, metadata, queue_derive)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/iarequest.py", line 154, in prepare_headers
    super(S3PreparedRequest, self).prepare_headers(headers)
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 409, in prepare_headers
    check_header_validity(header)
  File "/usr/local/lib/python3.5/dist-packages/requests/utils.py", line 756, in check_header_validity
    "not %s" % (value, type(value)))
requests.exceptions.InvalidHeader: Header value 0 must be of type str or bytes, not <class 'int'>
```

**Comment by saper** [comment]
Yes, this looks like a new check in 2.11.0

**Comment by saper** [comment]
@vxbinaca can you see if #152 checks that one for you? (probably downgrading Python requests module would help, too).

**Comment by vxbinaca** [comment]
What value do you want me to wrap in ```'```? The item name?

**Comment by saper** [comment]
I don't understand... just apply [the change](https://github.com/jjjake/internetarchive/pull/152/files) to the archive or just replace your `file.py` with a [modified version](https://raw.githubusercontent.com/saper/internetarchive/3986637f7accd4e96a06e278276be17beae75e24/internetarchive/files.py).

**Comment by vxbinaca** [comment]
I downgraded requests to 2.9.0 and it's still there, for reference, my installed requests when this problem was discovered was 2.10.0

**Comment by vxbinaca** [comment]
Wait a second, I downgraded it in pip3 as well and now it works now, so yes this appears to be a fix. You can merge that PR.

**Comment by saper** [comment]
@vxbinaca did you try the newest requests version with my patch?
