### ISSUE TITLE
Updating metadata in bulk

### ISSUE THREAD

**Issue by NewberryDIS** [jjjake/internetarchive#156]
I am trying to add a metadata field to 78 items that are already on the internet archive using ia metadata --spreadsheet=metadata.csv
It uploaded about half before giving this error:

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\ia.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\internetarchive\cli\ia.py", line 155, in m
ain
    sys.exit(ia_module.main(argv, session))
  File "c:\python27\lib\site-packages\internetarchive\cli\ia_metadata.py", line
143, in main
    item = session.get_item(row['identifier'])
  File "c:\python27\lib\site-packages\internetarchive\session.py", line 216, in
get_item
    item_class = self.ITEM_MEDIATYPE_TABLE.get(mediatype, Item)
TypeError: unhashable type: 'list'

I am not sure why it would have worked for 34 items but not for the rest, any ideas what to look for in order to fix this?

thanks!

**Comment by NewberryDIS** [comment]
Well the issue seems to be with just one item, when I removed it the rest loaded fine. Not sure what was wrong with it but this is soved.

**Comment by jjjake** [comment]
@NewberryDIS can you provide me with the spreadsheet, or just the row that this happened with? My email is on my profile.

Thanks for reporting!
