### ISSUE TITLE
ia upload not working behind http proxy

### ISSUE THREAD

**Issue by hargup** [jjjake/internetarchive#160]
I'm encountering the following error while using command line tool of internetarchive behind the http proxy of my university.

```
$ ia upload --spreadsheet=metadata2.csv                                                                            master [f655cd5] modified untracked
1981TN25:
Traceback (most recent call last):
  File "/home/hargup/anaconda/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/home/hargup/anaconda/lib/python2.7/site-packages/internetarchive/cli/ia.py", line 155, in main
    sys.exit(ia_module.main(argv, session))
  File "/home/hargup/anaconda/lib/python2.7/site-packages/internetarchive/cli/ia_upload.py", line 221, in main
    r = _upload_files(item, local_file, upload_kwargs, prev_identifier, session)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/internetarchive/cli/ia_upload.py", line 76, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/internetarchive/item.py", line 742, in upload
    request_kwargs=request_kwargs)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/internetarchive/item.py", line 607, in upload_file
    **request_kwargs)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/internetarchive/session.py", line 343, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.us.archive.org', port=443): Max retries exceeded with url: /1981TN25/1981TN25.pdf (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2284db250>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by saper** [comment]
How is your proxy configured? Environment variables? Which ones? Do you need to use proxy authentication?

**Comment by hargup** [comment]
The proxy is configured through environment variables and doesn't need authentication.
