### ISSUE TITLE
'Item has been taken offline' when it's not

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#195]
```
:: Uploading /home/vxbinaca/.tubeup/downloads/TSF_Chats_with_Veeh_-_Biological_Determinism-AXpVomv2oqQ...
2017-05-17 06:37:38,393 - internetarchive.item - INFO - uploaded TSF_Chats_with_Veeh_-_Biological_Determinism-AXpVomv2oqQ.mp4 to https://s3.us.archive.org/youtube-AXpVomv2oqQ/TSF_Chats_with_Veeh_-_Biological_Determinism-AXpVomv2oqQ.mp4
2017-05-17 06:37:38,393 - internetarchive.item - INFO - TSF_Chats_with_Veeh_-_Biological_Determinism-AXpVomv2oqQ.mp4 successfully uploaded to https://archive.org/download/youtube-AXpVomv2oqQ/TSF_Chats_with_Veeh_-_Biological_Determinism-AXpVomv2oqQ.mp4 and verified, deleting local copy
2017-05-17 06:38:23,243 - internetarchive.item - ERROR -  error uploading TSF_Chats_with_Veeh_-_Biological_Determinism-AXpVomv2oqQ.description to youtube-AXpVomv2oqQ, Access Denied - This item has been taken offline
Traceback (most recent call last):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/internetarchive/item.py", line 645, in upload_file
    response.raise_for_status()
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.us.archive.org/youtube-AXpVomv2oqQ/TSF_Chats_with_Veeh_-_Biological_Determinism-AXpVomv2oqQ.description

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vxbinaca/.local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 263, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 208, in upload_ia
    item.upload(vid_files, metadata=meta, retries=9001, request_kwargs=dict(timeout=9001), delete=True)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/internetarchive/item.py", line 771, in upload
    request_kwargs=request_kwargs)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/internetarchive/item.py", line 665, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading TSF_Chats_with_Veeh_-_Biological_Determinism-AXpVomv2oqQ.description to youtube-AXpVomv2oqQ, Access Denied - This item has been taken offline
```

Edit:

By the time you see this this item will be uploaded because it's a channel that needs an emergency rip so I'm restarting the rip from this point. However I've encountered this multiple times.

**Comment by jjjake** [comment]
Thanks for the report @vxbinaca.

To be clear -- you're getting this error, but it seems to be transient? What version of `internetarchive` is this happening with?

**Comment by vxbinaca** [comment]
```[vxbinaca@ragnvaldr archive-progress]$ ia --version
1.5.0```

**Comment by vxbinaca** [comment]
I haven't seen this in weeks. I've since done numerous huge channel dumps with zero of this hickup.

Closing because it's not relevant anymore. If it crops back up I'll re-open.

**Comment by jjjake** [comment]
Thanks for following up, @vxbinaca! : )
