### ISSUE TITLE
'timeout' no longer appears to be a valid flag

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#200]
```
Traceback (most recent call last):
  File "/home/vxbinaca/.local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 263, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 208, in upload_ia
    item.upload(vid_files, metadata=meta, retries=9001, request_kwargs=dict(timeout=9001), delete=True)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/internetarchive/item.py", line 830, in upload
    request_kwargs=request_kwargs)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/internetarchive/item.py", line 690, in upload_file
    **request_kwargs)
TypeError: send() got multiple values for keyword argument 'timeout'
```

Going to take a peek at my script in a second, however I did notice the version bump scanning the output of my VPS shell.

**Comment by jjjake** [comment]
@vxbinaca Thanks for the report. This was caused by adding a default timeout to upload in the last release. 

 0ef3035 should fix this.

**Comment by vxbinaca** [comment]
Thanks, Jake. Always much appreciated.
