### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by dkl3** [jjjake/internetarchive#202]
I've been dealing with this for the last 24 or so hours, and it's been really frustrating.

Output:

uploading /id: [################################] 1/1 - 00:00:00
Traceback (most recent call last):
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/item.py", line 645, in upload_file
    response.raise_for_status()
  File "/home/USER/gs-venv/lib/python3.4/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://s3.us.archive.org/warc-www_thegreatkaroo_com/id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/gs-venv/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/cli/ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/cli/ia_upload.py", line 212, in main
    for _r in _upload_files(item, files, upload_kwargs):
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/cli/ia_upload.py", line 78, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/item.py", line 739, in upload
    request_kwargs=request_kwargs)
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/item.py", line 658, in upload_file
    msg = get_s3_xml_text(exc.response.content)
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/utils.py", line 172, in get_s3_xml_text
    p = parseString(xml_str)
  File "/usr/lib/python3.4/xml/dom/minidom.py", line 1970, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.4/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.4/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 49

**Comment by jjjake** [comment]
Thanks for the report @dkl3. Do you mind if I try to upload a file called `id` to `warc-www_thegreatkaroo_com`? It looks like what's currently there is a 0 byte file. I'd like to try and replicate it.

You could also insert a `print(xml_str)` after line 172 in `/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/utils.py`. That should at least print out the XML error message which will be helpful for debugging.

There's another, secondary, bug here too. It's failing to parse the XML (maybe it's not XML) error message. I thought I addressed this recently. I'll take another look.

**Comment by dkl3** [comment]
i'll give you a down load to a warc to try on. I deleted This error occurs in both 1.5.0 and 1.6.0. And for me, it crashes regardless of 0-byte file or not. the file "id" is not 0-bytes. I have to keep restarting again and again, hoping the grab-site warc download will finish uploading.

OK, here's the output:

  _File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/item.py", line 645, in upload_file
    response.raise_for_status()
  File "/home/USER/gs-venv/lib/python3.4/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://s3.us.archive.org/warc-www_bosavern_co_za/all_start_urls

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/gs-venv/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/cli/ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/cli/ia_upload.py", line 212, in main
    for _r in _upload_files(item, files, upload_kwargs):
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/cli/ia_upload.py", line 78, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/item.py", line 739, in upload
    request_kwargs=request_kwargs)
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/item.py", line 658, in upload_file
    msg = get_s3_xml_text(exc.response.content)
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/utils.py", line 173, in get_s3_xml_text
    _msg = _get_tag_text('Message', p)
  File "/home/USER/gs-venv/lib/python3.4/site-packages/internetarchive/utils.py", line 164, in _get_tag_text
    elements = xml_obj.getElementsByTagName(tag_name)
AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'_

**Comment by dkl3** [comment]
In other words, it crashes at random, whenever it wants to, it looks like.

**Comment by jjjake** [comment]
Yeah, the issue is not it being a 0 byte file. 0 byte files should be fine, and I'd like to support them.

Looks like that print statement didn't quite work as I expected. What I'm after is the response content from the S3 request. The secondary bug I mentioned is preventing it from being printed currently.

I'll try to reproduce, and go from there.

**Comment by dkl3** [comment]
thank you very much :)

**Comment by dkl3** [comment]
b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>500 Internal Server Error</title>\n</head><body>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error or\nmisconfiguration and was unable to complete\nyour request.</p>\n<p>Please contact the server administrator at \n info@archive.org to inform them of the time this error occurred,\n and the actions you performed just before this error.</p>\n<p>More information about this error may be available\nin the server error log.</p>\n<hr>\n<address>Apache/2.4.7 (Ubuntu) Server at s3.us.archive.org Port 80</address>\n</body></html>\n

Additionally, I got this message just now.

**Comment by vxbinaca** [comment]
I was getting some S3 problems yesterday. I just re-ripped what I was doing where it snapped off when I was using Tubeup. Just chiming in I had a similar problem with S3.

**Comment by jjjake** [comment]
Thanks @dkl3... well, that's not a very helpful message.

I'll take a closer look server side.

**Comment by jjjake** [comment]
Still investigating, but I'm getting reports from others as well too now. I am going to be AFK this morning, but I'll follow up later today.

**Comment by jjjake** [comment]
@dkl3 this should now be resolved. Please let me know if you continue to experience issues. Thanks again!
