### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'backports.csv' distribution was not found and is required by internetarchive

### ISSUE THREAD

**Issue by daavve** [jjjake/internetarchive#217]
Hi, I am the package maintainer for this program on Arch Linux:  https://aur.archlinux.org/packages/python-internetarchive/

Unfortunately,  I always get the following error message when trying to do anything with the "ia" command:

```
$ ia
Traceback (most recent call last):
  File "/usr/bin/ia", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'backports.csv' distribution was not found and is required by internetarchive

```

Never seen anything like this before, please let me know if you need any more info.

-Dave

**Comment by jjjake** [comment]
Thanks for maintaining the Arch Linux pacakge, @daavve!

I'm not very familiar with Arch Linux packages, but I noticed that `backports.csv` is not listed as a dependency on https://aur.archlinux.org/packages/python-internetarchive/. Could that be causing the issue?

Here's the backports.csv repo: https://pypi.python.org/pypi/backports.csv

What happens when you try to install it manually with `python setup.py install`?

**Comment by daavve** [comment]
Thank you pointer to the backports.csv package.  The name sounded so much like a file name that I forgot to check I was missing a python package.  I added the dependencies my package and everything seems to work.

-Dave

**Comment by jjjake** [comment]
Awesome, that's great to hear! Thanks again for maintaining the Arch Linux package, that's really great! : )
