### ISSUE TITLE
Persistent ReadTimeout while uploading many files

### ISSUE THREAD

**Issue by mistydemeo** [jjjake/internetarchive#221]
I have a directory structure containing roughly 7800 files that I'm uploading. I've noticed that, a few hundred files in, I consistently get a `requests.exceptions.ReadTimeout` while uoloading. The exception's unhandled and isn't affected by the `--retries` commandline option; as a result, there doesn't seem to be a way for me to resume from the file I was uploading when the exception hit.

Steps to reproduce:

1. Run `ia upload item_name directory`, where `directory` is a directory containing a large number of files.

Expected results:

The whole structure is (eventually) uploaded.

Actual results:

The `ReadTimeout` eventually occurs.

Let me know if there's anything I can do to help debug this. I've provided the full traceback. I'm using Python 3.6.3 as installed via Homebrew, with internetarchive 1.7.3 installed via pip.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='s3.us.archive.org', port=443): Read timed out. (read timeout=120)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/internetarchive/cli/ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "/usr/local/lib/python3.6/site-packages/internetarchive/cli/ia_upload.py", line 216, in main
    for _r in _upload_files(item, files, upload_kwargs):
  File "/usr/local/lib/python3.6/site-packages/internetarchive/cli/ia_upload.py", line 80, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/usr/local/lib/python3.6/site-packages/internetarchive/item.py", line 799, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python3.6/site-packages/internetarchive/item.py", line 691, in upload_file
    **request_kwargs)
  File "/usr/local/lib/python3.6/site-packages/internetarchive/session.py", line 353, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='s3.us.archive.org', port=443): Read timed out. (read timeout=120)
```

**Comment by mjb2010** [comment]
I got this a couple of times, too, when uploading a large number of small directories (4 files per directory, each file a few megabytes) via a spreadsheet. The first timeout happened after about 30 directories had been uploaded and the second happened pretty quickly after that, so it does seem to be somewhat random. None of the folders were that much bigger than any of the others.

**Comment by jjjake** [comment]
Thanks for the reports @mistydemeo and @mjb2010. I'm investigating.

Can you guys send me the identifiers that you're getting this timeout with? You can email me if you'd prefer, my email address is on my profile.

**Comment by mistydemeo** [comment]
The identifier I've been having the timeout with is `sound_canvas_midi_collection`.

**Comment by jjjake** [comment]
Thanks @mistydemeo. I'll have a chance to take a closer look next week.

The retry parameter should definitely force a retry on 503s (i.e. getting rate-limited). That's a bug, if you're experiencing this. Maybe it's that all of the retries are failing, and you're seeing the error message from the final retry attempt failing? `ia --debug upload ...` might be helpful in diagnosing this. It will log each retry into a file called `internetarchive.log`.

BTW, we support thousands of files in single items (I think the hard limit is 100k, but we usually recommend against getting close to that), but it might make more sense to upload your material to multiple items, and we could create a collection for you? Whatever you think is best. You would get fewer 503s this way as well, as we rate-limit on a per-item basis and at the user level separately.

More information on archive.org what we consider an Item is available here: http://internetarchive.readthedocs.io/en/latest/items.html

I'll follow up once I'm able to take a closer look, thanks again!

**Comment by Coloradohusky** [comment]
I've been getting this error a lot too recently, however my uploads only have between three to five files per item
