### ISSUE TITLE
Persistently recurring SSL/Windows Socket errors when using ia upload --spreadsheet

### ISSUE THREAD

**Issue by jeffgerhard** [jjjake/internetarchive#227]
Hi,

For about a month I have experienced regular errors when trying to use `ia upload --spreadsheet=uploading.csv`-style uploads from a Windows terminal. Previously I hadn't used the cli for a while, so I'm not sure when this issue cropped up, but I used to do the same thing in the past regularly without error. I'm not totally sure what these error messages mean and it's possible that it has something to do with my local configuration or my networking settings at work.

I'm trying to put together a workflow that will allow for bulk uploads of numerous items from a handful of different Windows workstations. So, using Macs or Linux is not really an option. If I can't get this to work I'll revise my plans and switch to Python (or maybe curl) solutions, but I've been frustrated that I can't get `ia` to work reliably.

**Description:** I am trying to upload files using spreadsheets, in batches of around 15-30 items per sheet. Sometimes I can get an entire sheet to upload with `ia` but in the majority of cases, I hit SSL errors like the one below. Googling the WSAECONNABORTED errors has not helped me understand what is going on. I'm using Windows 7 Enterprise 64-bit, Anaconda Python 3.5.2, internetarchive version 1.7.4 (and this issue predates 1.7.4 since I upgraded when hitting this problem several weeks ago). Attempting to include `--retries` and `--debug` doesn't seem to make any difference, and the debug logs don't provide any useful info.

Would love to hear any suggestions before I give up on `ia`! Thanks.

Here is the most recent of these errors, where one item uploaded and then the second one failed:

F:\dc_court_appeals_recs_briefs\v33_v34\ia>ia --debug upload --spreadsheet=uploading.csv --retries=11
dc_circ_1909_2064_healey_v_maroney:
 uploading dc_circ_1909_2064_healey_v_maroney.pdf: [################################] 29/29 - 00:01:09
dc_circ_1909_2058_goodman_v_wren:
Traceback (most recent call last):an_v_wren.pdf: [                                ] 1/38 - 00:00:59
  File "c:\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 304, in _send_until_done
    return self.connection.send(data)
  File "c:\anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1462, in send
    self._raise_ssl_error(self._ssl, result)
  File "c:\anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1370, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (10053, 'WSAECONNABORTED')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "c:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\anaconda3\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "c:\anaconda3\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "c:\anaconda3\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "c:\anaconda3\lib\http\client.py", line 936, in _send_output
    self.send(message_body)
  File "c:\anaconda3\lib\http\client.py", line 905, in send
    self.sock.sendall(datablock)
  File "c:\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 316, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "c:\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 311, in _send_until_done
    raise SocketError(str(e))
OSError: (10053, 'WSAECONNABORTED')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "c:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\anaconda3\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\anaconda3\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "c:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "c:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\anaconda3\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "c:\anaconda3\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "c:\anaconda3\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "c:\anaconda3\lib\http\client.py", line 936, in _send_output
    self.send(message_body)
  File "c:\anaconda3\lib\http\client.py", line 905, in send
    self.sock.sendall(datablock)
  File "c:\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 316, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "c:\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 311, in _send_until_done
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(10053, 'WSAECONNABORTED')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\ia.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\internetarchive\cli\ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "c:\anaconda3\lib\site-packages\internetarchive\cli\ia_upload.py", line 243, in main
    session)
  File "c:\anaconda3\lib\site-packages\internetarchive\cli\ia_upload.py", line 80, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "c:\anaconda3\lib\site-packages\internetarchive\item.py", line 831, in upload
    request_kwargs=request_kwargs)
  File "c:\anaconda3\lib\site-packages\internetarchive\item.py", line 691, in upload_file
    **request_kwargs)
  File "c:\anaconda3\lib\site-packages\internetarchive\session.py", line 368, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "c:\anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "c:\anaconda3\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10053, 'WSAECONNABORTED')",))
 uploading dc_circ_1909_2058_goodman_v_wren.pdf: [################################] 1/38 - 00:00:09
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name='dc_circ_1909_2058_goodman_v_wren.pdf'>
c:\anaconda3\lib\socket.py:646: ResourceWarning: unclosed <socket.socket fd=784, family=AddressFamily.AF_INET, type=Sock
etKind.SOCK_STREAM, proto=0, laddr=('141.161.244.78', 53532), raddr=('207.241.225.48', 443)>
sys:1: ResourceWarning: unclosed <socket object at 0x00000000048BC458>`

**Comment by jjjake** [comment]
@jeffgerhard My apologies for not replying sooner.

Are you able to email me (my email is on my profile) a copy of the spreadsheet you were getting this error with?

I've been getting various connection error reports similar to this, and have not been able to sort it out. However, I was finally able to replicate and resolve a similar error someone else was running into just now.

Their issue ended up being a problem with how the request data was formatted. It ended up being a problem with the metadata they were submitting. I'm wondering if that's what's going on here.

Thanks!
