### ISSUE TITLE
File object upload crashing

### ISSUE THREAD

**Issue by palewire** [jjjake/internetarchive#241]
I am trying to upload a string object I create on the file when I generate a new key in my collection. The plan is to upload more media files to this "batch" later. But for starters I just want to put in a README."

```python
class MyDjangoModel(models.Model):
    # ... blah blah ...
    def create_ia_batch(self):
        logger.debug("Creating IA batch for {}".format(self.ia_batch_id))
        internetarchive.upload(
            self.ia_batch_id,
            [self.get_ia_batch_readme(),],
            metadata=self.ia_batch_metadata,
            access_key=settings.IA_ACCESS_KEY_ID,
            secret_key=settings.IA_SECRET_ACCESS_KEY,
            checksum=False,
            verbose=True
        )
        return internetarchive.get_item(self.ia_batch_id)

    def get_ia_batch_readme(self):
        """
        Returns a README file to be uploaded with the batch item to Internet Archive.
        """
        import cStringIO
        output = cStringIO.StringIO()
        txt = '# Screenshots of the {} homepage in {}'.format(
            self.site.name,
            dateformat(self.timestamp, 'F Y')
        )
        output.write(txt)
        output.close()
        return output
```

But when I run `obj.create_ia_batch()`` I get this error:

```python
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/palewire/.virtualenvs/pastpages.org/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/palewire/.virtualenvs/pastpages.org/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/palewire/.virtualenvs/pastpages.org/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/palewire/.virtualenvs/pastpages.org/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/palewire/Code/pastpages.org/archive/management/commands/testbackfill.py", line 15, in handle
    obj.get_or_create_ia_batch()
  File "/home/palewire/Code/pastpages.org/archive/models.py", line 379, in get_or_create_ia_batch
    return self.create_ia_batch(), True
  File "/home/palewire/Code/pastpages.org/archive/models.py", line 395, in create_ia_batch
    verbose=True
  File "/home/palewire/.virtualenvs/pastpages.org/local/lib/python2.7/site-packages/internetarchive/api.py", line 285, in upload
    request_kwargs=request_kwargs)
  File "/home/palewire/.virtualenvs/pastpages.org/local/lib/python2.7/site-packages/internetarchive/item.py", line 771, in upload
    total_files = recursive_file_count(files, item=self, checksum=False)
  File "/home/palewire/.virtualenvs/pastpages.org/local/lib/python2.7/site-packages/internetarchive/utils.py", line 233, in recursive_file_count
    f = f[0]
TypeError: 'cStringIO.StringO' object has no attribute '__getitem__'
```

What am I doing wrong? The docs suggest uploading file objects is allowed but I can only get it to work if I write out the files to the filesystem (which I'd prefer not to do.)

**Comment by palewire** [comment]
I wonder if this exception [here](https://github.com/jjjake/internetarchive/blob/master/internetarchive/utils.py#L235):

```python
            try:
                f = f[0]
                is_dir = os.path.isdir(f)
            except AttributeError:
                is_dir = False
```

Should be:

```python
            try:
                f = f[0]
                is_dir = os.path.isdir(f)
            except (AttributeError, TypeError):
                is_dir = False
```

**Comment by jjjake** [comment]
Thanks for the report @palewire.

I think f2a4add should resolve your issue. Note that you still need to name the file-like object by either setting the `name` attribute, or providing `upload` with a dict like `{'myfile.txt': output}`. Does that make sense?

Let me know if you have any questions or if you still experience any issues with this update. Thanks!
