### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by ahundt** [jjjake/internetarchive#275]
There appears to be quite a few file handle leaks (just open without a with statement). That may have led to the following error:
```
 warning: s3 is overloaded, sleeping for 5 seconds and retrying. 100 retries left.
 warning: s3 is overloaded, sleeping for 5 seconds and retrying. 100 retries left.
Traceback (most recent call last):
  File "costar_block_stacking_ia_upload.py", line 148, in <module>
  File "costar_block_stacking_ia_upload.py", line 121, in main
  File "/home/ahundt/src/internetarchive/internetarchive/item.py", line 860, in upload
  File "/home/ahundt/src/internetarchive/internetarchive/item.py", line 720, in upload_file
  File "/home/ahundt/src/internetarchive/internetarchive/session.py", line 370, in send
  File "/home/ahundt/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
  File "/home/ahundt/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
  File "/home/ahundt/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
  File "/home/ahundt/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 346, in _make_request
  File "/home/ahundt/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
  File "/home/ahundt/.local/lib/python2.7/site-packages/urllib3/connection.py", line 326, in connect
  File "/home/ahundt/.local/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 313, in ssl_wrap_socket
  File "/home/ahundt/.local/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 416, in load_verify_locations
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 528, in load_verify_locations
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
OpenSSL.SSL.Error: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file
', 'system lib')]
```

we fixed a few using with statements at https://github.com/jjjake/internetarchive/pull/274/files but there may be more, or a separate issue. Thanks!

**Comment by jjjake** [comment]
I think this should now be fixed in 1ac200cbbbe3bb039b50ffc1181798e3471281cc
