### ISSUE TITLE
TypeError on 'ia upload --checksum' when files are skipped

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#281]
When using the `--checksum` option with `ia upload` and when all files have already been uploaded correctly, i.e. no upload takes place, `ia` crashes with a `TypeError` inside Requests (paths removed):

    Traceback (most recent call last):
      File ".../ia", line 11, in <module>
        sys.exit(main())
      File ".../site-packages/internetarchive/cli/ia.py", line 159, in main
        sys.exit(ia_module.main(argv, session))
      File ".../site-packages/internetarchive/cli/ia_upload.py", line 225, in main
        for _r in _upload_files(item, files, upload_kwargs):
      File ".../site-packages/internetarchive/cli/ia_upload.py", line 105, in _upload_files
        if responses and responses[-1] and responses[-1].status_code != 200:
      File ".../site-packages/requests/models.py", line 671, in __bool__
        return self.ok
      File ".../site-packages/requests/models.py", line 697, in ok
        self.raise_for_status()
      File ".../site-packages/requests/models.py", line 928, in raise_for_status
        if 400 <= self.status_code < 500:
    TypeError: unorderable types: int() <= NoneType()

Versions: internetarchive 1.8.1 and Requests 2.18.4 on Python 3.4 on Debian.

**Comment by JustAnotherArchivist** [comment]
Apparently, this is not entirely restricted to runs where all files are skipped. I just finished uploading an item with `--checksum`, and after uploading all files, it crashed with a very similar traceback:

    Traceback (most recent call last):
      File ".../ia", line 11, in <module>
        sys.exit(main())
      File ".../site-packages/internetarchive/cli/ia.py", line 159, in main
        sys.exit(ia_module.main(argv, session))
      File ".../site-packages/internetarchive/cli/ia_upload.py", line 228, in main
        if (not _r) or (not _r.ok):
      File ".../site-packages/requests/models.py", line 671, in __bool__
        return self.ok
      File ".../site-packages/requests/models.py", line 697, in ok
        self.raise_for_status()
      File "../site-packages/requests/models.py", line 928, in raise_for_status
        if 400 <= self.status_code < 500:
    TypeError: unorderable types: int() <= NoneType()

Glancing over the code, I think that this second crash probably happens whenever at least one file is skipped; fortunately, it is only triggered at the very end of the run, so it doesn't actually impact the upload itself in any way. Further, both crashes seem to be caused by `internetarchive.item.Item.upload_file` returning an empty `requests.Response` object when skipping based on the checksum, which of course doesn't have a value for `status_code` set.

**Comment by vxbinaca** [comment]
What version are you using? This reminds me of a bug that was squashed a few months ago.

**Comment by JustAnotherArchivist** [comment]
> Versions: internetarchive 1.8.1 and Requests 2.18.4 on Python 3.4 on Debian.

I looked at the changes on master since 1.8.1, and you're right, this is identical to #260 (not sure why I didn't find that issue when I searched). It looks like it has been fixed on master but not released yet.

Closing since this is a duplicate of #260.
