### ISSUE TITLE
Files cannot be deleted from items that are full

### ISSUE THREAD

**Issue by AGSPhoenix** [jjjake/internetarchive#294]
```
phoenix@debian:~$ ia delete <FullItem> path/to/LargeFile -H x-archive-keep-old-version:0
Deleting files from <FullItem>
 deleting: path/to/LargeFile and all derivative files.
Traceback (most recent call last):
  File "/home/phoenix/.local/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/home/phoenix/.local/lib/python3.5/site-packages/internetarchive/cli/ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "/home/phoenix/.local/lib/python3.5/site-packages/internetarchive/cli/ia_delete.py", line 138, in main
    retries=args['--retries'])
  File "/home/phoenix/.local/lib/python3.5/site-packages/internetarchive/files.py", line 355, in delete
    resp.raise_for_status()
  File "/home/phoenix/.local/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.us.archive.org/<FullItem>/path/to/LargeFile
1 phoenix@debian:~$
```
To find out why, I made this edit to `ia_delete.py` around line 138:
```
[...]
        except requests.exceptions.RetryError as e:
            print(' error: max retries exceeded for {0}'.format(f.name), file=sys.stderr)
            errors = True
            continue
        except requests.exceptions.HTTPError as e: # <= new exception handler
            print("delete error:")
            print()
            print(e.response.content)
            print()
            raise
```
Which prints:
```
delete error:

b"<?xml version='1.0' encoding='UTF-8'?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>This item total number of bytes(1134253
428522) is over the per item size limit of 1099511627776. Please contact info@archive.org for help fitting your data into the archive.</Resource><RequestId
>68668829-eb88-4df7-b5c7-955d9899a0a1</RequestId></Error>"
```
It doesn't seem reasonable to completely lock an item if it gets too big. This doesn't seem to be a problem with the library, but the archive's software. Apologies if this isn't the right place to report this.

This occurs when deleting files from the history folder as well as regular files, both with and without the 'keep old version' header.

**Comment by jjjake** [comment]
I passed this along to the team that manages our S3 API. They said they'll try to fix ASAP.

**Comment by jjjake** [comment]
This should now be fixed.

**Comment by AGSPhoenix** [comment]
Fix confirmed; thanks Jake.
