### ISSUE TITLE
SSLError The write operation timed out

### ISSUE THREAD

**Issue by alifazeli** [jjjake/internetarchive#296]
Hi
After number of uploads (less than 300) when i use --spreadsheet upload i get this massage and i should perform command again everytime.
i use
./ia upload --spreadsheet=uploading-d4.csv --retries=100 --sleep=100

  File "/home/archive/ia/.bootstrap/_pex/pex.py", line 468, in execute_entry
  File "/home/archive/ia/.bootstrap/_pex/pex.py", line 486, in execute_pkg_resources
  File "/root/.pex/install/internetarchive-1.8.1-py2.py3-none-any.whl.d81b82447552eee4d27268dc3c5680c518b77fe4/internetarchive-1.8.1-py2.py3-none-any.whl/internetarchive/cli/ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "/root/.pex/install/internetarchive-1.8.1-py2.py3-none-any.whl.d81b82447552eee4d27268dc3c5680c518b77fe4/internetarchive-1.8.1-py2.py3-none-any.whl/internetarchive/cli/ia_upload.py", line 252, in main
    session)
  File "/root/.pex/install/internetarchive-1.8.1-py2.py3-none-any.whl.d81b82447552eee4d27268dc3c5680c518b77fe4/internetarchive-1.8.1-py2.py3-none-any.whl/internetarchive/cli/ia_upload.py", line 86, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/root/.pex/install/internetarchive-1.8.1-py2.py3-none-any.whl.d81b82447552eee4d27268dc3c5680c518b77fe4/internetarchive-1.8.1-py2.py3-none-any.whl/internetarchive/item.py", line 860, in upload
    request_kwargs=request_kwargs)
  File "/root/.pex/install/internetarchive-1.8.1-py2.py3-none-any.whl.d81b82447552eee4d27268dc3c5680c518b77fe4/internetarchive-1.8.1-py2.py3-none-any.whl/internetarchive/item.py", line 710, in upload_file
    **request_kwargs)
  File "/root/.pex/install/internetarchive-1.8.1-py2.py3-none-any.whl.d81b82447552eee4d27268dc3c5680c518b77fe4/internetarchive-1.8.1-py2.py3-none-any.whl/internetarchive/session.py", line 370, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "/root/.pex/install/requests-2.19.1-py2.py3-none-any.whl.9c19d1f49965483c8e82326b964ec1050dff6851/requests-2.19.1-py2.py3-none-any.whl/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/root/.pex/install/requests-2.19.1-py2.py3-none-any.whl.9c19d1f49965483c8e82326b964ec1050dff6851/requests-2.19.1-py2.py3-none-any.whl/requests/adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='s3.us.archive.org', port=443): Max retries exceeded with url: /ktp2019-bk3423/ktp2019-bk3423.pdf (Caused by SSLError(SSLError('The write operation timed out',),))
 uploading ktp2019-bk3423.pdf: [################################] 3/7 - 00:02:01

 its possible that its because of my internet connection. so is it possible to set proxy ai ?
and is it possible to set sleep between retries 2 hours for example? or any other solution?

thank you for support

my csv file attached

[uploading-d4.txt](https://github.com/jjjake/internetarchive/files/3076380/uploading-d4.txt)

**Comment by lokeshh** [comment]
I'm facing the same issue.

```
╰─ ia upload shaiva_hymns "/Users/lokesh/Documents/personal/शैव सिद्धान्त/manuscripts/shaiva hymns.pdf" --metadata="mediatype:texts" --retries 10
shaiva_hymns:
 uploading shaiva hymns.pdf:   3%|███▉                                                                                                                                         | 12/428 [14:13<9:55:01, 85.82s/MiB]Traceback (most recent call last):
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
    ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<6 lines>...
        enforce_content_length=enforce_content_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connection.py", line 459, in request
    self.send(chunk)
    ~~~~~~~~~^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1057, in send
    self.sock.sendall(data)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1263, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1232, in send
    return self._sslobj.write(data)
           ~~~~~~~~~~~~~~~~~~^^^^^^
TimeoutError: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
    ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<6 lines>...
        enforce_content_length=enforce_content_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connection.py", line 459, in request
    self.send(chunk)
    ~~~~~~~~~^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1057, in send
    self.sock.sendall(data)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1263, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1232, in send
    return self._sslobj.write(data)
           ~~~~~~~~~~~~~~~~~~^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lokesh/.local/bin/ia", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/cli/ia.py", line 150, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/cli/ia_upload.py", line 137, in <lambda>
    parser.set_defaults(func=lambda args: main(args, parser))
                                          ~~~~^^^^^^^^^^^^^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/cli/ia_upload.py", line 308, in main
    for _r in _upload_files(item, files, upload_kwargs):
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/cli/ia_upload.py", line 153, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/item.py", line 1366, in upload
    resp = self.upload_file(body,
                            key=key,
    ...<14 lines>...
                            request_kwargs=request_kwargs,
                            set_scanner=set_scanner)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/item.py", line 1177, in upload_file
    response = self.session.send(prepared_request,
                                 stream=True,
                                 **request_kwargs)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/session.py", line 554, in send
    raise e
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/session.py", line 551, in send
    reraise_modify(e, e.request.url, prepend=False)  # type: ignore
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/session.py", line 548, in send
    r = super().send(request, **kwargs)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', TimeoutError('The write operation timed out')), 'https://s3.us.archive.org/shaiva_hymns/shaiva%20hymns.pdf')
[1]    60349 segmentation fault  ia upload shaiva_hymns  --metadata="mediatype:texts" --retries 10
```

**Comment by lokeshh** [comment]
I'm facing the same issue.

```
╰─ ia upload shaiva_hymns "/Users/lokesh/Documents/personal/शैव सिद्धान्त/manuscripts/shaiva hymns.pdf" --metadata="mediatype:texts" --retries 10
shaiva_hymns:
 uploading shaiva hymns.pdf:   3%|███▉                                                                                                                                         | 12/428 [14:13<9:55:01, 85.82s/MiB]Traceback (most recent call last):
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
    ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<6 lines>...
        enforce_content_length=enforce_content_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connection.py", line 459, in request
    self.send(chunk)
    ~~~~~~~~~^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1057, in send
    self.sock.sendall(data)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1263, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1232, in send
    return self._sslobj.write(data)
           ~~~~~~~~~~~~~~~~~~^^^^^^
TimeoutError: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
    ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<6 lines>...
        enforce_content_length=enforce_content_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/urllib3/connection.py", line 459, in request
    self.send(chunk)
    ~~~~~~~~~^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1057, in send
    self.sock.sendall(data)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1263, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1232, in send
    return self._sslobj.write(data)
           ~~~~~~~~~~~~~~~~~~^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lokesh/.local/bin/ia", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/cli/ia.py", line 150, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/cli/ia_upload.py", line 137, in <lambda>
    parser.set_defaults(func=lambda args: main(args, parser))
                                          ~~~~^^^^^^^^^^^^^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/cli/ia_upload.py", line 308, in main
    for _r in _upload_files(item, files, upload_kwargs):
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/cli/ia_upload.py", line 153, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/item.py", line 1366, in upload
    resp = self.upload_file(body,
                            key=key,
    ...<14 lines>...
                            request_kwargs=request_kwargs,
                            set_scanner=set_scanner)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/item.py", line 1177, in upload_file
    response = self.session.send(prepared_request,
                                 stream=True,
                                 **request_kwargs)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/session.py", line 554, in send
    raise e
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/session.py", line 551, in send
    reraise_modify(e, e.request.url, prepend=False)  # type: ignore
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/internetarchive/session.py", line 548, in send
    r = super().send(request, **kwargs)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/lokesh/.local/pipx/venvs/internetarchive/lib/python3.13/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', TimeoutError('The write operation timed out')), 'https://s3.us.archive.org/shaiva_hymns/shaiva%20hymns.pdf')
[1]    60349 segmentation fault  ia upload shaiva_hymns  --metadata="mediatype:texts" --retries 10
```
