### ISSUE TITLE
Multiple No-Love's on attempted installations on OpenSUSE

### ISSUE THREAD

**Issue by androclus** [jjjake/internetarchive#300]
Hey, all..

I have been an ia cli-user for years. Something lately is just not working. (I am OpenSUSE Tumbleweed on an amd64 32GB RAM system.)  Let me know if there is any other information I can provide.

Below are three attempts I made to get an ia executable downloaded and running: via binary download, via git, and via pip. None of these worked.

**Attempted install via direct binary download**

```
$ curl -LOs https://archive.org/download/ia-pex/ia
$ chmod +x ia
$ ./ia --help
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 367, in execute
  File ".bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 410, in _execute
  File ".bootstrap/_pex/pex.py", line 468, in execute_entry
  File ".bootstrap/_pex/pex.py", line 482, in execute_pkg_resources
  File ".bootstrap/pkg_resources/__init__.py", line 2297, in resolve
  File "/home/jeff/.pex/install/internetarchive-1.8.5-py2.py3-none-any.whl.0749beeb0c64b2168053f35fe9c039127438232f/internetarchive-1.8.5-py2.py3-none-any.whl/internetarchive/__init__.py", line 45, in <module>
    from internetarchive.item import Item
  File "/home/jeff/.pex/install/internetarchive-1.8.5-py2.py3-none-any.whl.0749beeb0c64b2168053f35fe9c039127438232f/internetarchive-1.8.5-py2.py3-none-any.whl/internetarchive/item.py", line 48, in <module>
    from internetarchive.utils import IdentifierListAsItems, get_md5, chunk_generator, \
  File "/home/jeff/.pex/install/internetarchive-1.8.5-py2.py3-none-any.whl.0749beeb0c64b2168053f35fe9c039127438232f/internetarchive-1.8.5-py2.py3-none-any.whl/internetarchive/utils.py", line 35, in <module>
    from xml.dom.minidom import parseString
ImportError: No module named xml.dom.minidom
$ _
```
**Attempted Installation via git**
```
$ git clone git://github.com/jjjake/internetarchive.git
Cloning into 'internetarchive'...
remote: Enumerating objects: 258, done.
remote: Counting objects:   0% (1/258)   remote: Counting objects:   1% (3/258).. (etc.)
Resolving deltas:   0% (0/4251)...Resolving deltas: 100% (4251/4251), done.
$ cd internetarchive/
$ lh
total 112K
-rw-r--r-- 1 jeff users  355 Jun 29 20:00 AUTHORS.rst
-rw-r--r-- 1 jeff users 2.9K Jun 29 20:00 CONTRIBUTING.rst
drwxr-xr-x 3 jeff users 4.0K Jun 29 20:00 docs
-rw-r--r-- 1 jeff users  22K Jun 29 20:00 HISTORY.rst
drwxr-xr-x 3 jeff users 4.0K Jun 29 20:00 internetarchive
-rw-r--r-- 1 jeff users  34K Jun 29 20:00 LICENSE
-rw-r--r-- 1 jeff users 1.6K Jun 29 20:00 Makefile
-rw-r--r-- 1 jeff users   69 Jun 29 20:00 MANIFEST.in
-rw-r--r-- 1 jeff users  140 Jun 29 20:00 pex-requirements.txt
-rw-r--r-- 1 jeff users 1.4K Jun 29 20:00 README.rst
-rw-r--r-- 1 jeff users  359 Jun 29 20:00 setup.cfg
-rw-r--r-- 1 jeff users 1.8K Jun 29 20:00 setup.py
drwxr-xr-x 2 jeff users 4.0K Jun 29 20:00 snap
drwxr-xr-x 4 jeff users 4.0K Jun 29 20:00 tests
-rw-r--r-- 1 jeff users  231 Jun 29 20:00 tox.ini
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools
$ pip install setuptools
Requirement already satisfied: setuptools in /usr/lib/python3.7/site-packages (41.0.1)
$ _
```

**Attempted installation via pip**
```
$ sudo pip install internetarchive
[sudo] password for root: 
Collecting internetarchive
Downloading https://files.pythonhosted.org/packages/24/16/cbfd26d59eacc9880df23af11da09f9b9c0fcac4ddc68d3c863140714a0f/internetarchive-1.8.5-py2.py3-none-any.whl (85kB)
    |███▉                            | 10kB 2.5MB/s eta 0:00:01    |███████▊                        | 20kB 4.2MB/s eta 0:00:01    |███████████▌                    | 30kB 5.2MB/s eta 0:00:01    |███████████████▍                | 40kB 3.7MB/s eta 0:00:01    |███████████████████▏            | 51kB 4.1MB/s eta 0:00:01    |███████████████████████         | 61kB 4.8MB/s eta 0:00:01    |██████████████████████████▉     | 71kB 5.2MB/s eta 0:00:01    |██████████████████████████████▊ | 81kB 5.8MB/s eta 0:00:01    |████████████████████████████████| 92kB 5.1MB/s 
Requirement already satisfied: docopt<0.7.0,>=0.6.0 in /usr/lib/python3.7/site-packages (from internetarchive) (0.6.2)
Requirement already satisfied: backports.csv in /usr/lib/python3.7/site-packages (from internetarchive) (1.0.7)
Requirement already satisfied: requests<3.0.0,>=2.9.1 in /usr/lib/python3.7/site-packages (from internetarchive) (2.22.0)
Requirement already satisfied: total-ordering in /usr/lib/python3.7/site-packages (from internetarchive) (0.1.0)
Requirement already satisfied: six<2.0.0,>=1.0.0 in /usr/lib/python3.7/site-packages (from internetarchive) (1.12.0)
Requirement already satisfied: jsonpatch>=0.4 in /usr/lib/python3.7/site-packages (from internetarchive) (1.23)
Requirement already satisfied: schema>=0.4.0 in /usr/lib/python3.7/site-packages (from internetarchive) (0.7.0)
Requirement already satisfied: clint<0.6.0,>=0.4.0 in /usr/lib/python3.7/site-packages (from internetarchive) (0.5.1)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.7/site-packages (from requests<3.0.0,>=2.9.1->internetarchive) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.7/site-packages (from requests<3.0.0,>=2.9.1->internetarchive) (2.8)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.7/site-packages (from requests<3.0.0,>=2.9.1->internetarchive) (1.25.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.7/site-packages (from requests<3.0.0,>=2.9.1->internetarchive) (2019.3.9)
Requirement already satisfied: jsonpointer>=1.9 in /usr/lib/python3.7/site-packages (from jsonpatch>=0.4->internetarchive) (2.0)
Requirement already satisfied: contextlib2==0.5.5 in /usr/lib/python3.7/site-packages (from schema>=0.4.0->internetarchive) (0.5.5)
Requirement already satisfied: args in /usr/lib/python3.7/site-packages (from clint<0.6.0,>=0.4.0->internetarchive) (0.1.0)
Installing collected packages: internetarchive
Successfully installed internetarchive-1.8.5
$ ia --help
Traceback (most recent call last):
  File "/usr/bin/ia", line 6, in <module>
    from internetarchive.cli.ia import main
  File "/usr/lib/python3.7/site-packages/internetarchive/__init__.py", line 45, in <module>
    from internetarchive.item import Item
  File "/usr/lib/python3.7/site-packages/internetarchive/item.py", line 44, in <module>
    from requests import Response
  File "/usr/lib/python3.7/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 81, in <module>
    util.PROTOCOL_TLS: OpenSSL.SSL.SSLv23_METHOD,
AttributeError: module 'urllib3.util' has no attribute 'PROTOCOL_TLS'
$ _
```

**Comment by jjjake** [comment]
I was able to replicate the `ImportError: No module named xml.dom.minidom`, but after instaling the `python-xml` package all installation methods worked for me.

I could not replicate the setuptools or urllib3 issues. Perhaps there's issues with your Python installation? Have you tried `pip install .` from the root of the github dir?

Thanks for the heads up, and let me know if there's anything else I can do to help troubleshoot this. Sorry for the troubles!

**Comment by androclus** [comment]
Hi jjjake.. Thanks for looking at this so quickly. And your suggestions were quite helpful.

**1. binary download**

This does now work after I sudo zypper in python-xml

I don't know.. maybe add a list of dependencies (including python-xml) to [the docs](https://archive.org/services/docs/api/internetarchive/installation.html)?

Or have a better error message, like, "You need python-xml"?

**2. git install**

Your suggestion to try `pip install .` worked perfectly -- thank you.

However, this still does not work with `python setup.py install` (the recommended/doc'd method). At least for me. And I do see pip list shows I have setuptools on the system.

Maybe it is after all a problem with my setup, who knows? But I do at least like having your alternative installation suggestion. Maybe add that to [the docs](https://archive.org/services/docs/api/internetarchive/installation.html), as well?

**3. pip install**

You're quite right, this was indeed a problem with my python installation: I had pip-installed urllib3, but openSUSE wants to install urllib 3 via its packaging system (zypper/rpm). So I just pip-uninstall-ed urllib3 and then did another `zypper dup` which installed urllib3 correctly, and then this pip install method worked fine.

**Comment by jjjake** [comment]
Yay, glad to hear you've got it sorted @androclus!

Yeah, there's some work that could be done here to make this work better. I'm not very familiar with opensuse, and am not sure why it requires installing the python-lxml package... I've never come across that on any other OS.

I'll keep this open, in case anybody else with more experience with opensuse has any input.

**Comment by androclus** [comment]
Sounds good. BTW, for myself, I just have resolved to use git. But because I kept forgetting this conversation, and which python install method worked for me (since the setup.py does not), I made simple a little install file for myself in the git directory. It looks like this:

~/git/internetarchive/install.sh:
```
#!/bin/bash
sudo pip install .
```
So to update, I now just do this:
```
~/git/internetarchive $ git pull
~/git/internetarchive $ ./install.sh
```

**Comment by JustAnotherArchivist** [comment]
The `xml` package has been part of the standard library since the ancient times. Having to install `python-xml` sounds like an OpenSUSE-specific thing. There isn't any such package on Debian-based distributions, for example, as it's included in `libpython3.9-stdlib` (on Sid). Unless you explicitly install the `python3-minimal` package, which warns in the description that it only contains essential modules, you'll always have it installed, as expected. I don't think packages should care about non-standard, weirdly packaged Python distributions that exclude packages from the standard library.

For your installation with git in the original issue, I bet this is a Python 2 vs 3 thing where you only have setuptools installed under Python 3, so you'd need to run `python3 setup.py develop` (or even the minor version like `python3.7` if you have multiple installed). Python 2 support is now dropped, so that shouldn't matter anymore. `pip install -e .` would be equivalent to that command and probably also would've worked given the other comments.

The `PROTOCOL_TLS` error under Python 3.7 suggests that your Python was built without the `ssl` module. That would naturally break anything TLS-related.

So overall, I think none of these errors are anything that needs to be fixed or even documented in `ia`. If the Python installation is broken, packages should be expected to not work correctly.

**Comment by androclus** [comment]
Thanks, all. I do not have the time to research and verify whether OpenSUSE packages "wierdly" or not. But wouldn't it perhaps be helpful to other OpenSUSE users (one of the most common and long-standing distros outside of Debian/Ubuntu) if the ia docs were simply augmented to include a line or two with my alternate instructions for OpenSUSE users?

**Comment by jjjake** [comment]
@androclus Yes, more documentation is always welcome. I'm not very familiar with OpenSUSE, so PRs are always welcome.

FWIW, I was able to run `sudo pip install internetarchive` on a fresh install of OpenSUSE, and everything worked just fine. It was using Python 3.6 though, which is no longer maintained by Python or supported by this library, as of the next release (v.3.0.0).

The binary does _not_ work due to requiring Python >=3.7.

Does `pip install internetarchive` work for you on a supported version of Python, @androclus?
