### ISSUE TITLE
"error uploading" "the specified bucket is not valid. - Bucket names should be ..."

### ISSUE THREAD

**Issue by tenleftfingers** [jjjake/internetarchive#304]
The uploader fails for me. I'm using the documented way. Am I using the <identifier> incorrectly or is this a bug? 

```
$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from internetarchive import upload
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
>>> md = dict(collection='Community Audio', title='My New Item', mediatype='audio')
>>> r = upload('<My New Item>', files=['./Deasc/foo.txt', './Deasc/help-me-rob.ogg'], metadata=md)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/internetarchive/api.py", line 297, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/internetarchive/item.py", line 889, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/internetarchive/item.py", line 751, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading foo.txt to <My New Item>, The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)
>>> 

```

**Comment by jjjake** [comment]
You need to select a unique archive.org identifier, and replace `<My New Item>` with it.

Read more about archive.org identifiers here: https://archive.org/services/docs/api/metadata-schema/index.html#archive-org-identifiers

Here's the documentation for the Python library and command-line tool: https://archive.org/services/docs/api/internetarchive/index.html
