### ISSUE TITLE
Can't upload: ConnectionAbortedError

### ISSUE THREAD

**Issue by FloPinguin** [jjjake/internetarchive#317]
Hi, I am running internetarchive 1.8.5 on python 3.7.3 (Win 10). 

`ia --config-file "./config/XxxXxx.ini" --debug upload "xxxxxxx-xxxxxxx" "./Input/xxxxxxx-xxxxxxx.7z.001" --metadata="title:XxxxXXX Xxxxxxxx" --metadata="mediatype:data" --metadata="collection:opensource_media" --metadata="description:X xxx xx XXX Xxxxxxx (Xxxxxx, Xxxxxx)" --metadata="subject:XxxxXXX;XXX;Xxxxx;Xxxxxxxxx;Xxxxxxxxxx;Xxx,Xxxxxxxx;Xxxx Xxxx Xxxxxxx"`

This batch file ("x" for privacy) works for a couple of seconds and I get some MB uploaded. But then I always get the following connection error (I already tried `--retries`, did not help) ("x" for privacy):

xxxxxxx-xxxxxxx:
Traceback (most recent call last): [                                ] 12/501 - 00:43:36
  File "f:\program files\python\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "f:\program files\python\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "f:\program files\python\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "f:\program files\python\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "f:\program files\python\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "f:\program files\python\lib\http\client.py", line 1055, in _send_output
    self.send(chunk)
  File "f:\program files\python\lib\http\client.py", line 977, in send
    self.sock.sendall(data)
  File "f:\program files\python\lib\ssl.py", line 1015, in sendall
    v = self.send(byte_view[count:])
  File "f:\program files\python\lib\ssl.py", line 984, in send
    return self._sslobj.write(data)
ConnectionAbortedError: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\program files\python\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "f:\program files\python\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "f:\program files\python\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "f:\program files\python\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "f:\program files\python\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "f:\program files\python\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "f:\program files\python\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "f:\program files\python\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "f:\program files\python\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "f:\program files\python\lib\http\client.py", line 1055, in _send_output
    self.send(chunk)
  File "f:\program files\python\lib\http\client.py", line 977, in send
    self.sock.sendall(data)
  File "f:\program files\python\lib\ssl.py", line 1015, in sendall
    v = self.send(byte_view[count:])
  File "f:\program files\python\lib\ssl.py", line 984, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, 'Eine bestehende Verbindung wurde softwaregesteuert\r\ndurch den Hostcomputer abgebrochen', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\program files\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\program files\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Program Files\Python\Scripts\ia.exe\__main__.py", line 9, in <module>
  File "f:\program files\python\lib\site-packages\internetarchive\cli\ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "f:\program files\python\lib\site-packages\internetarchive\cli\ia_upload.py", line 224, in main
    for _r in _upload_files(item, files, upload_kwargs):
  File "f:\program files\python\lib\site-packages\internetarchive\cli\ia_upload.py", line 86, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "f:\program files\python\lib\site-packages\internetarchive\item.py", line 889, in upload
    request_kwargs=request_kwargs)
  File "f:\program files\python\lib\site-packages\internetarchive\item.py", line 718, in upload_file
    **request_kwargs)
  File "f:\program files\python\lib\site-packages\internetarchive\session.py", line 390, in send
    raise e
  File "f:\program files\python\lib\site-packages\internetarchive\session.py", line 387, in send
    reraise_modify(e, e.request.url, prepend=False)
  File "f:\program files\python\lib\site-packages\internetarchive\utils.py", line 310, in reraise_modify
    traceback)
  File "f:\program files\python\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "f:\program files\python\lib\site-packages\internetarchive\session.py", line 384, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "f:\program files\python\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "f:\program files\python\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'Eine bestehende Verbindung wurde softwaregesteuert\r\ndurch den Hostcomputer abgebrochen', None, 10053, None)), 'https://s3.us.archive.org/xxxxxxx-xxxxxxx/xxxxxxx-xxxxxxx.7z.001')
 uploading xxxxxxx-xxxxxxx.7z.001: [################################] 12/501 - 00:01:13

**Comment by jjjake** [comment]
@FloPinguin Would it be possible to post or email me more information about your command (i.e. the full metadata, identifier, and more info about the file) and your setup (i.e. Python version, ia version, etc.)? I'm unable to replicate this.

**Comment by FloPinguin** [comment]
@jjjake Sent you an email!
