### ISSUE TITLE
KeyError when using a UTF8 spreadsheet

### ISSUE THREAD

**Issue by ghost** [jjjake/internetarchive#328]
```
ia upload --spreadsheet=test.csv
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\ia.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\internetarchive\cli\ia.py", line 168, in main
    sys.exit(ia_module.main(argv, session))
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\internetarchive\cli\ia_upload.py", line 239, in main
    identifier = row['identifier']
KeyError: 'identifier'
```

If I delete the Byte Order Marker, the file works fine.

[test_utf8.txt](https://github.com/jjjake/internetarchive/files/4269893/test_utf8.txt)

**Comment by jjjake** [comment]
Can you please provide more details, I'm not sure I understand your issue.

**Comment by seritools** [comment]
Seems like the Byte Order Mark is not stripped:
https://github.com/jjjake/internetarchive/blob/master/internetarchive/cli/ia_upload.py#L2430

Using `utf-8-sig` instead seems to be the solution: https://stackoverflow.com/a/44573867/554577
