### ISSUE TITLE
"ia move" crashes on accent that's not in latin-1

### ISSUE THREAD

**Issue by msikma** [jjjake/internetarchive#344]
I was trying to move a file (`"09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.mp3"`) from the root of the item to a directory (`"András Schiff - Beethoven Lectures, Wigmore Hall (2004)/09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.mp3"`). It seems to crash on the á accent, the '\u0301' is the accent itself.

```
$ ia move "AndrasSchiffBeethovenLectures2004/09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.mp3" "AndrasSchiffBeethovenLectures2004/András Schiff - Beethoven Lectures, Wigmore Hall (2004)/09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.mp3"
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/internetarchive/session.py", line 489, in send
    reraise_modify(e, e.request.url, prepend=False)
AttributeError: 'UnicodeEncodeError' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ia", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/internetarchive/cli/ia.py", line 168, in main
    sys.exit(ia_module.main(argv, session))
  File "/usr/local/lib/python3.7/site-packages/internetarchive/cli/ia_move.py", line 73, in main
    r, src_file = ia_copy.main(argv, session, cmd='move')
  File "/usr/local/lib/python3.7/site-packages/internetarchive/cli/ia_copy.py", line 109, in main
    r = session.send(p)
  File "/usr/local/lib/python3.7/site-packages/internetarchive/session.py", line 492, in send
    raise e
  File "/usr/local/lib/python3.7/site-packages/internetarchive/session.py", line 486, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1293, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1225, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0301' in position 43: ordinal not in range(256)
```

I'm running Python 3.7.7 as my default `python` interpreter.

**Comment by msikma** [comment]
I should note, I'm not sure if it's even supported to move files into a directory using the CLI tool. I originally uploaded these files with the web uploader, which does allow you to drag in a directory.

Since I couldn't figure out a way to solve this I decided to just delete all the files in the directory and reupload them so they're in the root, which is fine in this case. But I'd still be interested to hear if there's some solution for this, or if maybe I was doing it wrong.

**Comment by jjjake** [comment]
@msikma what version of `ia` are you on? I believe this issue should have been fixed in v1.9.2.

I just tried to replicate this with the latest version, v1.9.3, and it worked fine:

```
» ia upload jj-test-2020-05-12 '09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.txt' -m collection:test_collection
jj-test-2020-05-12:
 [00:00<?,  uploading 09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.txt: 100%|█| 1/1 [00:00<00:00, 16.29MiB/s]
» ia mv 'jj-test-2020-05-12/09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.txt' 'jj-test-2020-05-12/András Schiff - Beethoven Lectures, Wigmore Hall (2004)/09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.txt'
success: moved jj-test-2020-05-12/09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.txt to jj-test-2020-05-12/András Schiff - Beethoven Lectures, Wigmore Hall (2004)/09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.txt
» ia ls jj-test-2020-05-12
András Schiff - Beethoven Lectures, Wigmore Hall (2004)/09 András Schiff - Beethoven Lecture-Recitals - Sonata No.9 in E, Op.141.txt
jj-test-2020-05-12_files.xml
jj-test-2020-05-12_meta.sqlite
jj-test-2020-05-12_meta.xml
```

**Comment by msikma** [comment]
Apologies, I was on a different computer and totally neglected to notice that its `ia` tool is still on an older version. I was on v1.9.0. My bad, I'll make sure to check next time!

**Comment by jjjake** [comment]
No problem, thanks for the report!
