### ISSUE TITLE
'Uploaded content is unacceptable' when uploading .txt file

### ISSUE THREAD

**Issue by Coloradohusky** [jjjake/internetarchive#358]
I was using my program, [InstaUp](https://github.com/Coloradohusky/InstaUp), to upload the user 'socostallionsband' when I got this error:
```
uploading /2018-04-20_23-20-53_UTC.txt: 100%|█| 1/
 error uploading /2018-04-20_23-20-53_UTC.txt: Uploaded content is unacceptable. - video file has improper extension, try one of these: .movie
Traceback (most recent call last):
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python38\lib\site-packages\internetarchive\item.py", line 958, in upload_file
    response.raise_for_status()
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Data for url: https://s3.us.archive.org/instagram-socostallionsband/2018-04-20_23-20-53_UTC.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "instaup.py", line 21, in uploadUser
    item.upload('./' + username + '/', verbose=True, checksum=True, delete=deletionStatus, metadata=dict(collection='opensource_media', subject='instagram', creator=username, title='Instagram Profile: ' + username, originalurl='https://www.instagram.com/' + username, scanner='InstaUp 1.0'), retries=9001, retries_sleep=60)
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python38\lib\site-packages\internetarchive\item.py", line 1071, in upload
    resp = self.upload_file(filepath,
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python38\lib\site-packages\internetarchive\item.py", line 979, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading /2018-04-20_23-20-53_UTC.txt to instagram-socostallionsband, Uploaded content is unacceptable. - video file has improper extension, try one of these: .movie

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python38\lib\site-packages\internetarchive\item.py", line 958, in upload_file
    response.raise_for_status()
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Data for url: https://s3.us.archive.org/instagram-socostallionsband/2018-04-20_23-20-53_UTC.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "instaup.py", line 43, in <module>
    uploadUser(username, delete)
  File "instaup.py", line 24, in uploadUser
    item.upload('./' + username + '/', verbose=True, checksum=True, delete=deletionStatus, metadata=dict(collection='opensource_media', subject='instagram', creator=username, title='Instagram Profile: ' + username, originalurl='https://www.instagram.com/' + username, scanner='InstaUp 1.0'), retries=9001, retries_sleep=60)
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python38\lib\site-packages\internetarchive\item.py", line 1071, in upload
    resp = self.upload_file(filepath,
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python38\lib\site-packages\internetarchive\item.py", line 979, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading /2018-04-20_23-20-53_UTC.txt to instagram-socostallionsband, Uploaded content is unacceptable. - video file has improper extension, try one of these: .movie
```
The text file in question is:
`MOVING ON!! The SCHS Drumline has just advanced to the FINALS in the WGI Percussion World Championships!! They will perform tomorrow morning at 9:20 am. Watch their performance live by going to WGI.org.  Let’s Go, SoCo!! We are so proud of you!! #southcountydrumline #southcountyhighschool #fcps #wgiworldchampionships #wgi2018  @socoplates`

I have no clue why it's giving me this error, other text files have worked just fine.
Item is [here](https://archive.org/details/instagram-socostallionsband).

**Comment by JustAnotherArchivist** [comment]
I bet it's because the file starts with `MOVI`, which are the magic bytes for [SGI movie files](http://fileformats.archiveteam.org/wiki/SGI_movie). So IA thinks it's a video file based on that and rejects the file with that error: "video file has improper extension, try one of these: .movie".

**Comment by Coloradohusky** [comment]
Hm, interesting! Is there any way I can work around that?

**Comment by nemobis** [comment]
I can reproduce the issue on the web interface too. A trick you can borrow from [GNU Mailman](https://list.org/) is to prefix such magic words with a ">"...

**Comment by jjjake** [comment]
@Coloradohusky Yes, it sounds like JustAnotherArchivist is correct here. I would suggest using the `>` prefix trick if possible. If you'd like to upload the file unaltered, email me and I can help you with a work around.

**Comment by JustAnotherArchivist** [comment]
Is a proper solution to this perhaps possible with file-level metadata? I saw that something's in development in that regard, and specifying the file format explicitly instead of having IA guess would solve it I imagine.

**Comment by jjjake** [comment]
@JustAnotherArchivist This wouldn't solve the issue. This is a spam filter, so user provided metadata is not trusted. Please email info@archive.org if you have any more questions about it, thanks!
