### ISSUE TITLE
"Broken Pipe" uploading 105MB file

### ISSUE THREAD

**Issue by tenleftfingers** [jjjake/internetarchive#373]
The upload starts well but breaks down part of the way through, usually around 40s or 50s / 105. The command I'm using is the same format as always and the full thing is available here: [https://amigausers.ie/uploader/aorguploader.php](https://amigausers.ie/uploader/aorguploader.php)

Can anyone help? Error message below:

`uploading AmigaIreland-S4E7-Feedback.mp3: [##############                  ] 46Traceback (most recent call last):
  File "/Users/amigaireland/ia/.bootstrap/_pex/pex.py", line 367, in execute
  File "/Users/amigaireland/ia/.bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File "/Users/amigaireland/ia/.bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File "/Users/amigaireland/ia/.bootstrap/_pex/pex.py", line 410, in _execute
  File "/Users/amigaireland/ia/.bootstrap/_pex/pex.py", line 468, in execute_entry
  File "/Users/amigaireland/ia/.bootstrap/_pex/pex.py", line 486, in execute_pkg_resources
  File "/Users/amigaireland/.pex/install/internetarchive-1.8.5-py2.py3-none-any.whl.0749beeb0c64b2168053f35fe9c039127438232f/internetarchive-1.8.5-py2.py3-none-any.whl/internetarchive/cli/ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "/Users/amigaireland/.pex/install/internetarchive-1.8.5-py2.py3-none-any.whl.0749beeb0c64b2168053f35fe9c039127438232f/internetarchive-1.8.5-py2.py3-none-any.whl/internetarchive/cli/ia_upload.py", line 224, in main
    for _r in _upload_files(item, files, upload_kwargs):
  File "/Users/amigaireland/.pex/install/internetarchive-1.8.5-py2.py3-none-any.whl.0749beeb0c64b2168053f35fe9c039127438232f/internetarchive-1.8.5-py2.py3-none-any.whl/internetarchive/cli/ia_upload.py", line 86, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/Users/amigaireland/.pex/install/internetarchive-1.8.5-py2.py3-none-any.whl.0749beeb0c64b2168053f35fe9c039127438232f/internetarchive-1.8.5-py2.py3-none-any.whl/internetarchive/item.py", line 889, in upload
    request_kwargs=request_kwargs)
  File "/Users/amigaireland/.pex/install/internetarchive-1.8.5-py2.py3-none-any.whl.0749beeb0c64b2168053f35fe9c039127438232f/internetarchive-1.8.5-py2.py3-none-any.whl/internetarchive/item.py", line 718, in upload_file
    **request_kwargs)
  File "/Users/amigaireland/.pex/install/internetarchive-1.8.5-py2.py3-none-any.whl.0749beeb0c64b2168053f35fe9c039127438232f/internetarchive-1.8.5-py2.py3-none-any.whl/internetarchive/session.py", line 390, in send
    raise e
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', error(32, 'Broken pipe')), 'https://s3.us.archive.org/Feedback/AmigaIreland-S4E7-Feedback.mp3')
 uploading AmigaIreland-S4E7-Feedback.mp3: [################################] 46/105 - 00:00:32
`

**Comment by tenleftfingers** [comment]
I downsampled the mp3 to make a 92MB file and the upload still failed at 32MB. That trick (keeping the file just under 100MB) worked in the past for a similar issue.
