### ISSUE TITLE
Many Time Out Errors When Uploading

### ISSUE THREAD

**Issue by decryption256** [jjjake/internetarchive#462]
Hi! When uploading content to the Internet Archive, the files are successfully uploaded, but quit with this error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out`

`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='s3.us.archive.org', port=443): Read timed out. (read timeout=120)`

`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/ia", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/internetarchive/cli/ia.py", line 170, in main
    sys.exit(ia_module.main(argv, session))
  File "/usr/local/lib/python3.8/dist-packages/internetarchive/cli/ia_upload.py", line 250, in main
    for _r in _upload_files(item, files, upload_kwargs):
  File "/usr/local/lib/python3.8/dist-packages/internetarchive/cli/ia_upload.py", line 98, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/internetarchive/item.py", line 1260, in upload
    resp = self.upload_file(body,
  File "/usr/local/lib/python3.8/dist-packages/internetarchive/item.py", line 1077, in upload_file
    response = self.session.send(prepared_request,
  File "/usr/local/lib/python3.8/dist-packages/internetarchive/session.py", line 570, in send
    raise e
  File "/usr/local/lib/python3.8/dist-packages/internetarchive/session.py", line 567, in send
    reraise_modify(e, e.request.url, prepend=False)
  File "/usr/local/lib/python3.8/dist-packages/internetarchive/utils.py", line 324, in reraise_modify
    six.reraise(ExceptClass,
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/internetarchive/session.py", line 564, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='s3.us.archive.org', port=443): Read timed out. (read timeout=120)"), 'https://s3.us.archive.org/everyday_practical_electronics-1999_01/everyday_practical_electronics-1999_01.cbr')`

Is there an issue with the version of Python I'm using here?

**Comment by kellyhaydon** [comment]
Was this issue addressed? I came here to submit a similar issue. I'm attempting to upload about a number of videos at once, but uploads in the past few weeks are occurring much slower than I've become accustomed to (over 8 hours for a 1 GB file). More relevant is that nearly every video gets a timeout error similar to the one above. I've tried the -retries flag but no dice. Uploading through the GUI has been my workaround, which makes me think it isn't a network issue. Let me know if I can provide more information.
