### ISSUE TITLE
OverflowError when uploading large file

### ISSUE THREAD

**Issue by ivan** [jjjake/internetarchive#57]
```
$ ~/.local/bin/ia upload "2014-03-06 grab of investigator.org.ua" investigator.org.ua.warc.gz investigator.org.ua.cdx    
2014-03-06 grab of investigator.org.ua:
Traceback (most recent call last):
  File "/home/ateam/.local/bin/ia", line 9, in <module>
    load_entry_point('internetarchive==0.5.7', 'console_scripts', 'ia')()
  File "/home/ateam/.local/lib/python2.7/site-packages/internetarchive/iacli/ia.py", line 81, in main
    ia_module.main(argv)
  File "/home/ateam/.local/lib/python2.7/site-packages/internetarchive/iacli/ia_upload.py", line 125, in main
    _upload_files(args, args['<identifier>'], local_file, upload_kwargs)
  File "/home/ateam/.local/lib/python2.7/site-packages/internetarchive/iacli/ia_upload.py", line 54, in _upload_files
    response = item.upload(local_file, **upload_kwargs)
  File "/home/ateam/.local/lib/python2.7/site-packages/internetarchive/item.py", line 510, in upload
    resp = self.upload_file(f, **kwargs)
  File "/home/ateam/.local/lib/python2.7/site-packages/internetarchive/item.py", line 437, in upload_file
    prepared_request = request.prepare()
  File "/home/ateam/.local/lib/python2.7/site-packages/internetarchive/iarequest.py", line 42, in prepare
    queue_derive=self.queue_derive,
  File "/home/ateam/.local/lib/python2.7/site-packages/internetarchive/iarequest.py", line 62, in prepare
    self.prepare_body(data, files)
  File "/home/ateam/.local/lib/python2.7/site-packages/requests/models.py", line 410, in prepare_body
    length = super_len(data)
  File "/home/ateam/.local/lib/python2.7/site-packages/requests/utils.py", line 50, in super_len
    return len(o)
OverflowError: long int too large to convert to int

$ ls -l ~/.local/lib/python2.7/site-packages/ | grep -i internetar
drwxrwxr-x 3 ateam ateam  4096 Apr 24 01:41 internetarchive
drwxrwxr-x 2 ateam ateam  4096 Apr 24 01:41 internetarchive-0.5.7.egg-info

$ python --version
Python 2.7.3

$ ls -l investigator.org.ua.warc.gz investigator.org.ua.cdx
-rw-rw-r-- 1 ateam ateam   84165932 Mar  6 02:45 investigator.org.ua.cdx
-rw-rw-r-- 1 ateam ateam 8974369559 Mar  6 02:45 investigator.org.ua.warc.gz
```

**Comment by jjjake** [comment]
@ivan This should now be fixed in https://github.com/jjjake/internetarchive/commit/6c9f77cb9b57296bc88278b5716c7a3bc32c3b43.
