### ISSUE TITLE
Specified bucket is not valid when uploading from session, even though it is unique and conforms to the suggested regex

### ISSUE THREAD

**Issue by Timonheu** [jjjake/internetarchive#641]
I am testing uploading an item with the following code (keys are omitted):
```Python
from internetarchive import get_session
config = {
    "s3": {"access": ACCESS_KEY, "secret": SECRET_KEY},
    "logging": {"level": "DEBUG"},
}

session = get_session(config=config)
md = {"collection": "test_collection", "title": "My New Item", "mediatype": "movies"}
item = session.get_item("H5LfUkFxk9eKno8vdE6ViG7b")
assert not item.exists # This assertion passes
print("Item to be uploaded does not yet exist.")
r = item.upload("test_file.txt", metadata=md)
r[0].status_code
```
The identifier has been randomly generated for this test, and conforms to the regex in the error message below.
When I run this I get the following output (file paths have been truncated):
```
Item to be uploaded does not exist.
Traceback (most recent call last):
  File ".../venv/lib/python3.10/site-packages/internetarchive/item.py", line 1102, in upload_file
    response.raise_for_status()
  File ".../venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://s3.us.archive.org/H5LfUkFxk9eKno8vdE6ViG7b/test_file.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../above_code.py", line 15, in <module>
    r = item.upload("test_file.txt", metadata=md)
  File ".../venv/lib/python3.10/site-packages/internetarchive/item.py", line 1273, in upload
    resp = self.upload_file(body,
  File ".../venv/lib/python3.10/site-packages/internetarchive/item.py", line 1127, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading test_file.txt to H5LfUkFxk9eKno8vdE6ViG7b, The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)
```
I am using internetarchive version 3.7.0 and running Python version 3.10.12.

The documentation for uploading an item is incomplete, as `item` is never initialized in the code snippet (https://archive.org/developers/tutorial-create-item.html). The documentation for `Item.upload()` (https://archive.org/developers/internetarchive/internetarchive.html?highlight=item%20upload#internetarchive.Item.upload) and `Item.upload_file()` state a new item will be created if it does not exist yet, but this is not the behavior shown.

Is there anything I missed/am doing wrong? The identifier seems valid and unique, I am experiencing the same issue with different identifiers, with both `upload()` and `upload_file()`. If I could contribute to the documentation to avoid this in the future I would be happy to, but I would first need to know the proper way to upload an item.

**Comment by jjjake** [comment]
Thanks for the report @Timonheu. We've received a few other reports like this, this week.

This is a strange one. Your code looks good to me, and I was able to create [this item](http://archive.org/details/jj-test-item-2024-04-04) with it after I changed the identifier and collection.

Note that you need to upload to an existing collection. I am wondering if that might be the issue, but due to a bug on archive.org you're getting the wrong error message? Can you retry running this code with the value of `collection` set to `test_collection`? Mine fails when I upload to a non-existing collection, but it does return an accurate error message:

```
error uploading test_file.txt to H5LfUkFxk9eKno8vdE6ViG7b, Uploaded content is unacceptable. - Item metadata collection value refers to nonexistant collection: H5LfUkFxk9eKno8vdE6ViG7b_collection
```

Your identifier, `H5LfUkFxk9eKno8vdE6ViG7b`, seems available as far as I can tell as well (we generally suggest more readable IDs, but I don't think we actively block IDs like this and it does match the regex in the error message).

Just to rule out more possible causes too, can you confirm `test_file.txt` is a valid text file (i.e. That it's not a binary file with a `.txt` extension. We do block this, but again, it should return a different error message)?

Thanks again for the report, I'll followup when I get more details from our team who works on our S3-like API.

**Comment by Timonheu** [comment]
Thank you very much for your reply.

I was unaware that the collection had to be created separately, thank you for bringing that to my attention.

Setting the collection to `test_collection` yields the same error message. I have verified that it is a valid text file. Also changing the identifier to something more readable does not work. I have tried both `heu_test_item_20240405` and `heu_test_item_20240405_22`.

**Comment by jjjake** [comment]
@Timonheu We haven't confirmed, but it sounds like this might be an archive.org bug that happens when a user changes their email address. It appears that it can be resolved by destroying and regenerating your S3 keys. You can do that here:

https://archive.org/account/s3.php

I'm going to close this thread as it seems to be an archive.org bug. My apologies for the issue, and hopefully we can get it resolved ASAP.

Please let me know if destroying and regenerating your keys doesn't help, or if you're not able to for any reason.
