### ISSUE TITLE
Updating the description metadata fails when it contains HTML

### ISSUE THREAD

**Issue by Digitoxin1** [jjjake/internetarchive#660]
When using the latest release (Version 5.0.0), If I try to update metadata using **ia metadata --spreadsheet**, if there is any html tags in the description column, I get the following error:

`Traceback (most recent call last):
  File "/usr/bin/ia", line 33, in <module>
    sys.exit(load_entry_point('internetarchive==1.9.9', 'console_scripts', 'ia')())
  File "/usr/lib/python3/dist-packages/internetarchive/cli/ia.py", line 170, in main
    sys.exit(ia_module.main(argv, session))
  File "/usr/lib/python3/dist-packages/internetarchive/cli/ia_metadata.py", line 269, in main
    responses.append(modify_metadata(item, metadata, args))
  File "/usr/lib/python3/dist-packages/internetarchive/cli/ia_metadata.py", line 88, in modify_metadata
    if not r.json()['success']:
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

This used to work fine before the shutdown, so I am not sure if this issue is an archive.org issue, or an issue with this version of the application.

**Comment by jjjake** [comment]
Thanks for the report @Digitoxin1. I have a fix that I hope to ship today. It will be in version 5.0.2.
