### ISSUE TITLE
SSL timeouts on item uploads kill Tubeup uploads

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#669]
```
An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:2417)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s3.us.archive.org', port=443): Max retries exceeded with url: /youtube-W0I17AvW4As/W0I17AvW4As.webm (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2417)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\tubeup\__main__.py", line 97, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\tubeup\TubeUp.py", line 415, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\tubeup\TubeUp.py", line 377, in upload_ia
    item.upload(files_to_upload, metadata=metadata, retries=9001,
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\internetarchive\item.py", line 1283, in upload
    resp = self.upload_file(body,
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\internetarchive\item.py", line 1095, in upload_file
    response = self.session.send(prepared_request,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\internetarchive\session.py", line 540, in send
    raise e
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\internetarchive\session.py", line 537, in send
    reraise_modify(e, e.request.url, prepend=False)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\internetarchive\session.py", line 534, in send
    r = super().send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vxbin\pipx\venvs\tubeup\Lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='s3.us.archive.org', port=443): Max retries exceeded with url: /youtube-W0I17AvW4As/W0I17AvW4As.webm (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2417)')))"), 'https://s3.us.archive.org/youtube-W0I17AvW4As/W0I17AvW4As.webm')
```

Is there a way to control SSL timeouts? We'll patch on our end if so, if not please consider implementing.

**Comment by jjjake** [comment]
As you might've guessed/known, `internetarchive` uses `requests` to make these calls. `request_kwargs=dict(timeout=9001)` gets handed off to `requests` when making the call to IA-S3.

I believe if only an int/float is provided as a timeout, it's considered a connection timeout (which includes the SSL handshake). You can also configure the read timeout by providing a tuple (e.g. `timeout=(9001, 300)`). More details on requests timeout parameter [here](https://requests.readthedocs.io/en/latest/user/advanced/#timeouts).

@vxbinaca If I'm understanding you correctly, you'd like to configure a lower timeout for SSL handshakes and keep the long timeout for everything else in the connection phase of the request? If so, I don't think that's possible, but I'm not certain.

IA-S3 has been very saturated recently, and I know others have been experiencing a lot of issues as well. I'll try to figure out what exactly the cause is of these SSL errors and see if there's anything we can do to make `internetarchive.upload` more reliable. Sorry for the trouble!
