### ISSUE TITLE
Unicode in x-archive-meta header keys fails on upload

### ISSUE THREAD

**Issue by eeejay** [jjjake/internetarchive#69]
When I try to upload something through a utf-8 encoded csv with Chinese characters, I get the following error. I tried doing urllib.parse.quote on the value with no success.

When I remove the unicode characters, it works fine.

Traceback (most recent call last):##########                ] 1/2 - 00:00:00
  File "/home/eitan/tmp/.amir/bin/ia", line 9, in <module>
    load_entry_point('internetarchive==0.7.1', 'console_scripts', 'ia')()
  File "/home/eitan/tmp/ia-wrapper/internetarchive/iacli/ia.py", line 81, in main
    ia_module.main(argv)
  File "/home/eitan/tmp/ia-wrapper/internetarchive/iacli/ia_upload.py", line 173, in main
    _upload_files(args, identifier, local_file, upload_kwargs, prev_identifier)
  File "/home/eitan/tmp/ia-wrapper/internetarchive/iacli/ia_upload.py", line 76, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/home/eitan/tmp/ia-wrapper/internetarchive/item.py", line 618, in upload
    resp = self.upload_file(body, key=key, **kwargs)
  File "/home/eitan/tmp/ia-wrapper/internetarchive/item.py", line 506, in upload_file
    response = self.http_session.send(prepared_request, stream=True)
  File "/home/eitan/tmp/.amir/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/home/eitan/tmp/.amir/lib/python2.7/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='s3.us.archive.org', port=80): Max retries exceeded with url: /EB_00024s2011.jpg/00024s2011.jpg (Caused by <class 'socket.error'>: [Errno 32] Broken pipe)

**Comment by johtso** [comment]
I'm experiencing this same issue. Although I'm confused as to why unicode characters in a filename would cause a non-ascii metadata key to exist..

```
~/M/m/t/staging
❯ l
주찬양 선교단 - 일어나라 빛을발하라 (MP3).zip     주찬양 선교단 - 일어나라 빛을발하라 (Side B).zip
주찬양 선교단 - 일어나라 빛을발하라 (Side A).zip

~/M/m/t/staging
❯ ia upload TapesssBlogDownloads * --no-derive --delete --checksum
/usr/local/bin/ia:5: UserWarning: Module _markerlib was already imported from /usr/local/lib/python2.7/site-packages/distribute-0.6.49-py2.7.egg/_markerlib/__init__.pyc, but /usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg is being added to sys.path
  from pkg_resources import load_entry_point
TapesssBlogDownloads:
/usr/local/lib/python2.7/site-packages/internetarchive/item.py:158: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if f.name == file_name:
Traceback (most recent call last):  빛을발하라 (MP3).zip: [##############                  ] 63/139 - 00:01:21
  File "/usr/local/bin/ia", line 9, in <module>
    load_entry_point('internetarchive==0.8.1', 'console_scripts', 'ia')()
  File "/usr/local/lib/python2.7/site-packages/internetarchive/iacli/ia.py", line 95, in main
    ia_module.main(argv)
  File "/usr/local/lib/python2.7/site-packages/internetarchive/iacli/ia_upload.py", line 185, in main
    _upload_files(args, args['<identifier>'], local_file, upload_kwargs)
  File "/usr/local/lib/python2.7/site-packages/internetarchive/iacli/ia_upload.py", line 78, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/usr/local/lib/python2.7/site-packages/internetarchive/item.py", line 633, in upload
    resp = self.upload_file(body, key=key, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/internetarchive/item.py", line 528, in upload_file
    response = self.http_session.send(prepared_request, stream=True)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='s3.us.archive.org', port=80): Max retries exceeded with url: /TapesssBlogDownloads/%E1%84%8C%E1%85%AE%E1%84%8E%E1%85%A1%E1%86%AB%E1%84%8B%E1%85%A3%E1%86%BC%20%E1%84%89%E1%85%A5%E1%86%AB%E1%84%80%E1%85%AD%E1%84%83%E1%85%A1%E1%86%AB%20-%20%E1%84%8B%E1%85%B5%E1%86%AF%E1%84%8B%E1%85%A5%E1%84%82%E1%85%A1%E1%84%85%E1%85%A1%20%E1%84%87%E1%85%B5%E1%86%BE%E1%84%8B%E1%85%B3%E1%86%AF%E1%84%87%E1%85%A1%E1%86%AF%E1%84%92%E1%85%A1%E1%84%85%E1%85%A1%20%28MP3%29.zip (Caused by <class 'socket.error'>: [Errno 32] Broken pipe)
```

What's the recommended workaround?
