### ISSUE TITLE
"Too many open files" when uploading 1020th file.

### ISSUE THREAD

**Issue by tungol** [jjjake/internetarchive#84]
On file number 1020 uploaded in a single session, I'm getting an error. Reproduced twice now, both times on the 1020th file. I can start up again and upload additional files to the same item.

Here's the traceback, parts in double square brackets are replacement generic values:

Traceback (most recent call last):
  File "/usr/bin/ia", line 9, in <module>
  File "/usr/lib/python2.6/site-packages/internetarchive/iacli/ia.py", line 95, in main
  File "/usr/lib/python2.6/site-packages/internetarchive/iacli/ia_upload.py", line 185, in main
  File "/usr/lib/python2.6/site-packages/internetarchive/iacli/ia_upload.py", line 78, in _upload_files
  File "/usr/lib/python2.6/site-packages/internetarchive/item.py", line 633, in upload
  File "/usr/lib/python2.6/site-packages/internetarchive/item.py", line 528, in upload_file
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 559, in send
  File "/usr/lib/python2.6/site-packages/requests/adapters.py", line 375, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='s3.us.archive.org', port=80): Max retries exceeded with url: /[[item identifier]]/[[filename]](Caused by <class 'socket.error'>: [Errno 24] Too many open files)

**Comment by jjjake** [comment]
I believe https://github.com/jjjake/internetarchive/pull/162 should address this issue. @tungol please comment if you continue to have issues in versions > 1.1.0.dev1.
