### ISSUE TITLE
Handle requests.exceptions.ConnectionError: HTTPConnectionPool

### ISSUE THREAD

**Issue by nemobis** [jjjake/internetarchive#86]
Maybe it's my fault or my machine/whatever, but this exception seems weird:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python2.7/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python2.7/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python2.7/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python2.7/dist-packages/apport/packaging_impl.py", line 20, in <module>
    import apt
  File "/usr/lib/python2.7/dist-packages/apt/__init__.py", line 34, in <module>
    apt_pkg.init_config()
SystemError: E:Opening configuration file /etc/apt/apt.conf.d/15pax-mark - ifstream::ifstream (13: Permission denied)

Original exception was:
Traceback (most recent call last):
  File "uploader.py", line 282, in <module>
    main()
  File "uploader.py", line 279, in main
    upload(wikis, config)
  File "uploader.py", line 114, in upload
    item = get_item('wiki-' + wikiname)
  File "/home/users/federico/.local/lib/python2.7/site-packages/internetarchive/api.py", line 26, in get_item
    return item.Item(identifier, metadata_timeout, config, max_retries, archive_session)
  File "/home/users/federico/.local/lib/python2.7/site-packages/internetarchive/item.py", line 99, in __init__
    self._json = self.get_metadata(metadata_timeout)
  File "/home/users/federico/.local/lib/python2.7/site-packages/internetarchive/item.py", line 123, in get_metadata
    resp = self.http_session.get(url, timeout=metadata_timeout)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in get
    return self.request('GET', url, **kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='archive.org', port=80): Max retries exceeded with url: /metadata/wiki-wikizaaksysteemnl (Caused by <class 'socket.error'>: [Errno 111] Connection refused)
```

**Comment by jjjake** [comment]
Metadata GET's are now retried 3 times by default, more can be specified like so:

```
>>> item = get_item('nasa', http_adapter_kwargs={'max_retries': 10})
>>> item.session.adapters['https://archive.org'].max_retries
Retry(total=300, connect=300, read=300, redirect=0)
```
