### ISSUE TITLE
Configuration fails on Debian stable

### ISSUE THREAD

**Issue by chronomex** [jjjake/internetarchive#89]
```
$ cat /etc/debian_version 
8.1
$ ia configure
Please enter your Archive.org credentials below to have your
Archive.org cookies and IA-S3 keys added to your config file.

Traceback (most recent call last):
  File "/usr/local/bin/ia", line 9, in <module>
    load_entry_point('internetarchive==0.8.5', 'console_scripts', 'ia')()
  File "/usr/local/lib/python3.4/dist-packages/internetarchive/iacli/ia.py", line 95, in main
    ia_module.main(argv)
  File "/usr/local/lib/python3.4/dist-packages/internetarchive/iacli/ia_configure.py", line 28, in main
    username=raw_input('Email address: '),
NameError: name 'raw_input' is not defined
```

If I change `raw_input` to `input`:

```
$ ia configure
Please enter your Archive.org credentials below to have your                    
Archive.org cookies and IA-S3 keys added to your config file.

Email address: my@email
Password: 
Traceback (most recent call last):
  File "/usr/local/bin/ia", line 9, in <module>
    load_entry_point('internetarchive==0.8.5', 'console_scripts', 'ia')()
  File "/usr/local/lib/python3.4/dist-packages/internetarchive/iacli/ia.py", line 95, in main
    ia_module.main(argv)
  File "/usr/local/lib/python3.4/dist-packages/internetarchive/iacli/ia_configure.py", line 54, in main
    fp.write(configfile)
TypeError: 'str' does not support the buffer interface
```

**Comment by saper** [comment]
I think you should try running ia. scripts under Python 2, not Python 3.

**Comment by chronomex** [comment]
Hmmm, it works just fine in python2, ok.

But: because of this bug https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1308714 I can't use it on the machine that I want to.  Anyway, that is my problem now, not yours.

**Comment by saper** [comment]
#83 indicates that uploads may work with Python 3 once you set it up. Didn't test that. I think it's just a minor nuisance.
